### ISSUE TITLE
zsh-completions require compinit in the .zshrc file?

### ISSUE THREAD

**Issue by daften** [zsh-users/zsh-completions#277]
Is that necessary, after changing the fpath?

**Comment by gilbertwyw** [comment]
I find that i need to put the fpath modification like this:
```
fpath=(
  /usr/local/share/zsh-completions
  /usr/local/share/zsh/site-functions
  $fpath
)

source $ZSH/oh-my-zsh.sh

# User configuration
```

wondering if there's more location-independent way of doing this. Was hoping that I can put it below that user configuration line.

**Comment by liangguohuan** [comment]
I finish install oh-my-zsh, then i add 
```
fpath=(/usr/local/share/zsh/zsh-completions/src $fpath)
```
to `.zshrc` at the beginning, but it still doesn't work, 
i must `compinit` in every `zsh`, then it can work.

who can tell me what's the problom ?

**Comment by gilbertwyw** [comment]
quote from `brew info zsh-completions`:

>You may also need to force rebuild `zcompdump`:
>
>  rm -f ~/.zcompdump; compinit

HTH

**Comment by liangguohuan** [comment]
hi, `gilbertwyw`, 
`i must compinit in every zsh, then it can work.` means i do it like you say, 
i saw the tips via `manual installation` before.

my system is ubuntu 14.04.

**Comment by apjanke** [comment]
Yes, you need to call `compinit` in your `.zshrc` so it is run every time the shell starts. That is how `zsh` initializes the completion system; it is normal.

**Comment by apjanke** [comment]
Sorry, disregard my last comment: I didn't see that some of you were running Oh My Zsh. OMZ calls `compinit` for you as part of the startup process, so you don't have to do it yourself.

The issue with OMZ and `compinit` here is (at least partly) that OMZ expects a different plugin structure than `zsh-completions` has. OMZ expects the definitions for all completion definitions to be in the root directory of the plugin. Its startup process goes like this:

* Add the root dir of each plugin to `$fpath`
* Run `compinit`
* Source each of the plugins' `<foo>.plugin.zsh` files to load them

Since `zsh-completion` uses `zsh-completion.plugin.zsh` to put its `src/` dir on `$fpath`, it doesn't happen until OMZ has already run `compinit`, so their completions aren't included. You can do another `compinit` after sourcing `~/.oh-my-zsh/oh-my-zsh.sh` to pick them up, though the multiple `compinit`s could be a performance issue.

**Comment by lfaoro** [comment]
add this to your `.zshrc`: 

`rm -f "$HOME/.zcompdump"; compinit`

problem solved

**Comment by Baneeishaque** [comment]
```
fpath=(/usr/local/share/zsh-completions $fpath)
rm -f "$HOME/.zcompdump"; compinit
source ~/.zshrc

```
Causes zsh to stuck on startup.

```
fpath=(/usr/local/share/zsh-completions $fpath)
rm -f "$HOME/.zcompdump"; compinit
```
Fixed the issue.
