### ISSUE TITLE
Yarn completion is very slow

### ISSUE THREAD

**Issue by ahmedelgabri** [zsh-users/zsh-completions#520]
Yarn completion is very slow when I do `$ yarn <tab>`, notice how long it takes after the first `<tab>` to show the list & also after the second `<tab>` to go to the first option. Any tips on how can I debug this? it seems to be only happening with `yarn` only, tried `ag`, `vagrant` & `jq` all are fast.

![slow](https://user-images.githubusercontent.com/63876/29430226-ebaa8250-8393-11e7-85d5-67057cc819c1.gif)

**Comment by syohex** [comment]
Because yarn completion does

1. Execute `yarn run --json`
2. Parse `1.` output and collect packageScript(`scripts` entries in package.json) and binCommands(scripts under `.node_modules/bin`) by `sed` and `tr` command
3. Construct completion list from static list(yarn subcommands) and `2.` list

As you know, we can use `yarn packageScript` instead of `yarn run packageScript` and `yarn some-command` instead of `./node-modules/.bin/some-command`. So yarn completion should do above procedures.

I suppose faster completion commands uses only static list for completion.

**Comment by gavindsouza** [comment]
Has this been resolved since or has my computer gotten a lot faster?

**Comment by syohex** [comment]
I'm not sure however`yarn run --json` is no longer used since https://github.com/zsh-users/zsh-completions/pull/827 for supporting newer yarn versions. It was replaced with zsh builtin functions and perl one liner. So I suppose yarn completion is faster than older one.

**Comment by Fridus** [comment]
Hi, Since update, completion for command `yarn` is not correct when script name contains `:`. 

By example `yarn migration:run`

**Comment by syohex** [comment]
I'll check later

**Comment by syohex** [comment]
@Fridus Thanks for reporting issue. I have fixed your issue at #836. Could you try latest version ?

**Comment by Fridus** [comment]
@syohex Fixed ! Thanks !

**Comment by syohex** [comment]
I suppose this issue has already been fixed.
