### ISSUE TITLE
Restore completion for hledger

### ISSUE THREAD

**Issue by fdw** [zsh-users/zsh-completions#585]
Hi,

I noticed that there had been a completion for [hledger](https://hledger.org), written by @Valodim, but it was removed in commit 0713143 because it had no licence header.
I'm wondering what need to happen to restore the completion, as I couldn't find an alternative and I'd much rather re-use something existing than write it from scratch.

Thanks!

**Comment by okapia** [comment]
If you can track down @Valodim, he/she would need to agree to specify a licence for the function, preferably the zsh licence so that it might make its way into zsh itself.

I think someone on #zsh on IRC was asking questions for work on an hledger completion not long ago so you could try asking there. Someone somewhere is bound to have something started. Failing that, I've got something half-finished for the old (non-h) ledger which might work as a starting point.

**Comment by Valodim** [comment]
Consider it licensed apache v2, feel free to re-add or build upon :+1:

**Comment by Valodim** [comment]
sure, go ahead
