### ISSUE TITLE
compadd of zsh is useless when input some char into command line

### ISSUE THREAD

**Issue by hq229075284** [zsh-users/zsh-completions#669]
Does the compadd command for ZSH not support completion when some characters are entered？

I have a executable file called 'index_for_test.js',and i add a shell script to .zshrc.

$PATH: 
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hanqing/Development/compadd-test`

the `index_for_test.js` at the root of `/Users/hanqing/Development/compadd-test`

```
./
├── dir1
│   ├── a.js
│   └── b.js
├── dir2
│   ├── a.ts
│   └── b.ts
└── index_for_test.js

total 24
drwxr-xr-x   6 hanqing  staff   192 11  4 13:45 .
drwxr-xr-x  10 hanqing  staff   320 11  4 13:42 ..
-rw-r--r--@  1 hanqing  staff  6148 11  4 14:04 .DS_Store
drwxr-xr-x   4 hanqing  staff   128 11  4 13:43 dir1
drwxr-xr-x   4 hanqing  staff   128 11  4 13:43 dir2
-rwxr-xr-x   1 hanqing  staff   155 11  4 13:50 index_for_test.js
```

```javascript
// index_for_test.js
#! /usr/bin/env node

const fs =require('fs')
const path=require('path')
const files=fs.readdirSync(path.join(process.cwd()))
console.log(files.join('\n'))
```

the script be added to .zshrc :
```shell
_index_for_test_completion() {
    local abc=(`index_for_test.js`)
    echo '\nabc:\n'
    echo $abc'\n'
    compadd -- $abc
}
compdef _index_for_test_completion index_for_test.js
```

When input `index_for_test.js` followed by input a space then press `tab`, it work find.But when input `index_for_test.js ../` then press `tab`,it does not show completion list, even if `compadd` accept the arguments.

## Image:
[normal: index_for_test.js][1]

[error: index_for_test.js ../][2]

## Expect
If this is my mistake,please let me know the reason,thanks.

In addition,if the behavior is right,I wonder that how to achieve completion like `cd` command;
[behavior of cd][3]

  [1]: https://i.stack.imgur.com/7x7Rn.png
  [2]: https://i.stack.imgur.com/Gq3DP.png
  [3]: https://i.stack.imgur.com/vcCpr.png

**Comment by okapia** [comment]
The current word on the command-line starts with the prefix "../". Your function then adds four potential completions: ".DS_Store", "dir1", "dir2" and "index_for_test.js". None of these four potential completions begin with your prefix so there are, as expected, no matches.

By default, completion matching is done against the current shell word. You need to manipulate IPREFIX, ISUFFIX, PREFIX and SUFFIX to alter this. For example, if you completion function did: `compset -P ../` then you might get four matches because you've moved the prefix over to the ignored prefix.

You've got other problems there, however. Don't try to reimplement file completion if all you're doing is filtering matched files.  And you'll likely have problems with filenames containing spaces.

Note that this is not the right place to be asking questions about how to write completion functions, There is a zsh-users mailing list for that. And if compadd was at fault here, you'd want the contact the zsh project and not this one.

**Comment by hq229075284** [comment]
Sorry, I thought here would be specific explanation of the use of ZSH completion, but the official documentation of ZSH does not have examples, so it seems confusing

**Comment by okapia** [comment]
The best explanation I know of is in book form, see http://www.bash2zsh.com/
Zsh itself comes with many examples, but they aren't marked up with comments pitched at people learning. There's some notes here at https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org

**Comment by hq229075284** [comment]
Thank you for your advice
