### ISSUE TITLE
No suffix alias completions found.

### ISSUE THREAD

**Issue by fffranks** [zsh-users/zsh-completions#779]
Hi, I have a problem with the plugin with the following message:

No suffix alias completions found.

I would like to know how I would solve this problem, a [friend](https://github.com/odilonscoelho) of mine tested it on his and gave the same thing, so I kick that may be the plugin that may have some bug or error!

Currently my zshrc is like this:

https://0x0.st/-ouk.txt

Thank you for your understanding, thank you...

Printscreen from my friend:
![odilon](https://user-images.githubusercontent.com/51012258/106417298-79d3d400-6432-11eb-8cdb-05a0f75b3a8d.jpg)

My Printscreen:
![suffix](https://user-images.githubusercontent.com/51012258/106417304-80624b80-6432-11eb-9528-102cc094054e.png)

**Comment by syohex** [comment]
It looks your problem is zsh-autocomplete issue. I suppose your warning is here(https://github.com/marlonrichert/zsh-autocomplete/blob/2c3c6dd37c81a2f33ac37b485645cb78ab6f6529/module/.autocomplete.config#L83-L85)

Please report this to [its issues](https://github.com/marlonrichert/zsh-autocomplete/issues).
